# Base image
FROM node:18

# Working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Clean install of dependencies
RUN npm install --omit=dev

# Copy the rest of the app
COPY . .

# Expose backend port
EXPOSE 5000

# Start app
CMD ["node", "app.js"]
